modified:   arg_handler.sh 	modified:   wireguard_user

diff --git a/wireguard_user b/wireguard_user
--- a/wireguard_user
+++ b/wireguard_user
@@ -64,8 +64,6 @@ check_install()	{
 }
 
 
-
-
 new_client_setup () {
 
 	# Locate the proper resolv.conf
@@ -120,6 +118,60 @@ EOF
 	wg addconf wg0 <(sed -n "/^# BEGIN_PEER $client/,/^# END_PEER $client/p" /etc/wireguard/wg0.conf)
 }
 
+delete_client ()  {
+
+	# This option could be documented a bit better and maybe even be simplified
+	# ...but what can I say, I want some sleep too
+	number_of_clients=$(grep -c '^# BEGIN_PEER' /etc/wireguard/wg0.conf)
+	if [[ "$number_of_clients" = 0 ]]; then
+		echo
+		echo "error: There are no existing clients!"
+		exit
+	fi
+	
+#	echo "Select the client to remove:"
+
+	grep '^# BEGIN_PEER' /etc/wireguard/wg0.conf | cut -d ' ' -f 3 | nl -s ') '
+
+			# read -p "Client: " client_number
+			
+			#until [[ "$client_number" =~ ^[0-9]+$ && "$client_number" -le "$number_of_clients" ]]; do
+			#	echo "$client_number: invalid selection."
+			#	read -p "Client: " client_number
+			#done
+			
+	client=$(grep '^# BEGIN_PEER' /etc/wireguard/wg0.conf | cut -d ' ' -f 3 | sed -n "$client_number"p)
+			
+			#echo
+			#read -p "Confirm $client removal? [y/N]: " remove
+			#until [[ "$remove" =~ ^[yYnN]*$ ]]; do
+			#	echo "$remove: invalid selection."
+			#	read -p "Confirm $client removal? [y/N]: " remove
+			#done
+			
+			#if [[ "$remove" =~ ^[yY]$ ]]; then
+				# The following is the right way to avoid disrupting other active connections:
+				# Remove from the live interface
+			
+	wg set wg0 peer "$(sed -n "/^# BEGIN_PEER $client$/,\$p" /etc/wireguard/wg0.conf | grep -m 1 PublicKey | cut -d " " -f 3)" remove
+				# Remove from the configuration file
+				sed -i "/^# BEGIN_PEER $client/,/^# END_PEER $client/d" /etc/wireguard/wg0.conf
+				echo
+				echo "$client removed!"
+			#else
+			#	echo
+			#	echo "$client removal aborted!"
+			#fi
+			exit
+
+
+
+}
+
+
+list_users()  {
+	grep '^# BEGIN_PEER' /etc/wireguard/wg0.conf | cut -d ' ' -f 3
+}
 
 
 # readings Args 
@@ -133,33 +185,36 @@ while :
 do
   case "$1" in
     -u | --user )
-      USERNAME="$2"
-      shift 2
-	  # Allow a limited set of characters to avoid conflicts
-	  client=$(sed 's/[^0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_-]/_/g' <<< "$USERNAME")
-      ;;
+		USERNAME="$2"
+		shift 2
+		# Allow a limited set of characters to avoid conflicts
+		client=$(sed 's/[^0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_-]/_/g' <<< "$USERNAME")
+		;;
     -a | --add )
-      ADD=true
-	  new_client_setup
-	shift 1
-	;;
+		ADD=true
+		new_client_setup
+		shift 1
+		;;
     -d | --del )
-      DEL=true
-	echo "del"
-	shift 1
-      ;;
+		DEL=true
+		echo "del"
+		shift 1
+		;;
+	-l | --list)
+		list_users
+		exit 2
     -h | --help)
-      help
-      exit 2
-      ;;
+		help
+		exit 2
+		;;
     --)
-      shift;
-      break
-      ;;
+		shift;
+		break
+		;;
     *)
-      echo "error: Unexpected option: $1"
-      break
-      ;;
+		echo "error: Unexpected option: $1"
+		break
+		;;
   esac
 done
 
